
project_id = "pppfbldpxqndjlgfghos"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
smtp_max_frequency = 60

[realtime]
enabled = true

[analytics]
enabled = false

[vector]
enabled = false

[functions]
[functions.process-order]
verify_jwt = false
[functions.get-orders]
verify_jwt = false
[functions.send-firebase-webhook]
verify_jwt = false
[functions.razorpay-payment]
verify_jwt = false
[functions.send-email]
verify_jwt = false
[functions.process-notifications]
verify_jwt = false
