// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pppfbldpxqndjlgfghos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwcGZibGRweHFuZGpsZ2ZnaG9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDQ5NDUsImV4cCI6MjA2MTQyMDk0NX0.KBGT_6v4JhcvfEe4fqV7ScWeJHjEZEVuQw5-otrDXbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);